services:
  backend:
    build:
      context: ./backend
      dockerfile: api/Dockerfile
    container_name: news_summarizer_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/api/.env
    volumes:
      - ./backend:/app
      - /app/node_modules

  backend_cron:
    build:
      context: ./backend
      dockerfile: cron_jobs/Dockerfile
    container_name: news_summarizer_backend_cron
    env_file:
      - ./backend/cron_jobs/.env
    depends_on:
      - backend
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: news_summarizer_frontend
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
